### ISSUE TITLE
updated logo suggestion

### ISSUE THREAD

**Issue by violoncelloCH** [deltachat/interface#15] opened 2019-01-27 15:14 UTC
Hi
I would suggest to update the delta chat logo to a more modern look:
![delta-v7-pathed-bgwhite](https://user-images.githubusercontent.com/22591354/51802768-6c851d00-224d-11e9-8d48-93690359548c.png) ![delta-v7-pathed](https://user-images.githubusercontent.com/22591354/51802773-727afe00-224d-11e9-9fb6-0cec51797ff7.png)
It uses the delta chat primary colour (#364e59) without any gradient making it more flat/modern.
With this colour and without the grey border it gives deltachat a characteristic look that doesn't look like a copy of whatsapp's icon.
![image](https://user-images.githubusercontent.com/22591354/51802859-51ff7380-224e-11e9-85fb-0aef1ff836c0.png)

any opinions? @r10s @hpk42 @ralphtheninja @angelo-fuchs

**Comment by angelo-fuchs** [comment] 2019-01-28 09:34
lgtm. Personally I would wait to see which LED color we settle on and then introduce that color in the logo as well.

**Comment by violoncelloCH** [comment] 2019-01-28 10:07
@angelo-fuchs that's a good idea! is there an issue/pr for that somewhere?
generally I think it's important for delta chat to have one representing colour, which people always associate to delta chat... so if we choose another colour, I would use this colour for the top bar (and the places where now #364e59 is used) too.

**Comment by angelo-fuchs** [comment] 2019-01-28 16:07
@violoncelloCH There is no issue for that (yet). I asked in the irc channel to have the poll linked here as soon as its done.

**Comment by violoncelloCH** [comment] 2019-01-28 21:13
@angelo-fuchs I missed that on irc... may I have a look at the poll?

**Comment by karissa** [comment] 2019-01-28 22:19
looks great! good idea.

**Comment by kermoshina** [comment] 2019-01-29 11:50
@violoncelloCH hey! The poll is in my Telegram blog/channel and is in Russian. The link: https://t.me/parisburns/4897 
Will post results today with translation.

**Comment by violoncelloCH** [comment] 2019-01-30 21:43
@kermoshina any news? :)

**Comment by angelo-fuchs** [comment] 2019-01-31 23:20
@violoncelloCH purple won, so the default LED color is now purple (as soon as the [PR](https://github.com/deltachat/deltachat-android/pull/686) is merged)

**Comment by r10s** [comment] 2019-02-01 20:06
not, afaik, actually there are no "official" plans to change the main or logo color.

**Comment by violoncelloCH** [comment] 2019-02-01 20:10
@r10s I'm just asking because @angelo-fuchs stated:
> lgtm. Personally I would wait to see which LED color we settle on and then introduce that color in the logo as well.

but I'm fine with keeping the current colour... we can always change at a later point...
so would you like me to create a PR for the new logo?

**Comment by r10s** [comment] 2019-02-01 22:46
i'm personally not up for a logo discussion currently. but other may be :)

**Comment by violoncelloCH** [comment] 2019-02-13 17:19
so anything I can do here? @angelo-fuchs @karissa @ralphtheninja 
I would really like to improve delta chat's logo :)

**Comment by angelo-fuchs** [comment] 2019-02-14 09:17
@violoncelloCH I personally don't feel very strongly one way or another. But it seems that you (and also some people on the support forum) do. So I suggest you coordinate with them and then bring it forward. I think this would be a good thing to also organize in a decentral setup like a survey or if you have fun with such: a competition. Or just collect the ones you (plural) think are good and post them all here (include the current one) and then we'll have a talk and pick the "best" one.

**Comment by hpk42** [comment] 2019-02-14 09:31
as @r10s i am not interested currently in participating in logo discussions. 
It's a lot of background caring/updating sites/apps work apart 
from the potential hours spend discussing it. 

There are many interesting UX and design issues, eg for the help pages 
to have nice graphics for how Delta Chat works, how DC interacts with 
the e-mail system, etc. where graphical/design contributions are more 
directly useful and help the project's overall communication 
and education efforts.

**Comment by violoncelloCH** [comment] 2019-02-14 14:15
thank you @angelo-fuchs and @hpk42 for clarifying!
I get your point that there are many other things (issues/features) to be done by developers and I don't want to waste your time with hard design questions. 
However I think that a great design is, apart from the features, still quite important for winning new users for the same reasons as klundry stated [here](https://support.delta.chat/t/proposal-logo-update/139/26).

@angelo-fuchs should I use the [existing forum thread](https://support.delta.chat/t/proposal-logo-update/139) for that or create a new (wiki post?) where everyone can add their proposals before voting?

@hpk42 I'm aware that deciding on a changed logo would mean some further work in updating it everywhere and I would be willing to help there as well (e.g. with creating PRs) wherever I can :)
Thank you for pointing me to the things I could do for the help pages! I would like to help there as well, but I feel that I would need some more information on what kind of graphics are needed and what they should explain exactly. However I could not find an issue / issues for that; is there some description/specification somewhere? :)

**Comment by angelo-fuchs** [comment] 2019-02-14 17:00
@violoncelloCH Use whatever thread you think is best.

**Comment by angelo-fuchs** [comment] 2019-02-14 17:40
@violoncelloCH in other news there are also issues that could use someone with an idea of colors, etc. but this gets off topic. Just send me an email (deltachat - at - sommerfuchs.info) and chat there.

**Comment by karissa** [comment] 2019-02-14 19:07
purple

**Comment by violoncelloCH** [comment] 2019-02-18 00:18
here is the forum entry for a comparison: https://support.delta.chat/t/logo-competition-vote/258
I already added a purple variant of my logo there :)

**Comment by Simon-Laux** [comment] 2023-07-05 18:54
let's discuss this on the forum. closing this as there is no actionable item and the issue is stale for years

**Closed by Simon-Laux** 2023-07-05 18:54 UTC
