### ISSUE TITLE
Mention that it's impossible to change password through DC alone

### ISSUE THREAD

**Issue by WofWca** [deltachat/interface#73] opened 2024-07-19 13:54 UTC
- Operating System (Linux/Mac/Windows/iOS/Android): Windows, Android
- Delta Chat Version: 1.46
- Expected behavior: It is made clear that you cannot update your password through Delta Chat - you have to do it through your email service and only then set the correct one in Delta Chat.
- Actual behavior: It looks like you can change your password through Delta Chat, like on any other service / messenger.
- Steps to reproduce the problem:
    1. Go to Advanced Settings
    2. Go to "Account and Password"
- Screenshots:

    ![image](https://github.com/user-attachments/assets/470e2f48-c77f-43e2-b2db-82c2bacba046)

- Logs: none

The issue was worsened by https://github.com/deltachat/deltachat-desktop/pull/4032) in Delta Chat desktop. But even when it is fixed, Delta Chat would still simply say something like "failed to authenticate" when you change your password and continue operating as usual (see https://github.com/deltachat/deltachat-desktop/pull/4033 ).

So it appears that these settings are only useful when
- you've changed your password outside of Delta Chat, which (I suppose) would make Delta Chat unable to use the account.
- You want to change the email address.

But I think simply adding a paragraph stating that you have to change the password outside of DC first would be good already.

Forum posts about changing password:
- https://support.delta.chat/t/view-and-change-account-password/3024?u=wofwca
- https://support.delta.chat/t/change-account-password/773?u=wofwca
- https://support.delta.chat/t/chatmail-technical-questions/2854/7?u=wofwca

**Comment by nicodh** [comment] 2024-09-27 04:59
This makes sense to me. Has there been any discussion on that before? @adbenitez  @r10s

**Comment by r10s** [comment] 2024-10-05 14:38
> Has there been any discussion on that before? @adbenitez @r10s

yes.

in the past, we got more complains about confusion between  _sign in_ or _sign up_ and _change password_.

we changed the wording slightly at https://github.com/deltachat/deltachat-android/pull/1256 then - this is where the **_Existing_ Password** comes from.

i think, the issue is smaller since then - in the linked forum entries, most ppl understand, that one cannot change the password (only the answer to the 2nd post can be read misleading). also, the dialog is "Advanced" now - esp. when it comes to changing password - where it was primary UI in the past. we have more complicated things in "Advanced" :)

so, well, not sure. if ppl are not reading the word **_Existing_**, they might not read additional explanations :)

still, we can easily refine the [`login_no_servers_hint` text below the password](https://github.com/deltachat/deltachat-android/blob/main/src/main/res/values/strings.xml#L595) field, however, this should _not_ result in more text than before, as otherwise chances are good ppl are not reading :)

**Comment by WofWca** [comment] 2024-10-06 08:23
IDK if a single word "existing" is enough to explain that this is not your usual "change the password" form, but rather a "log in" form. You could read it as "so, my existing password is this. Let me change my existing password".
If you're already logged in it doesn't make sense that there would be any password field other than a "change password" one.

**Comment by adbenitez** [comment] 2024-10-06 08:47
anyways, worse that can happen is: you try to change password, get an error and realize you can't change password there

**Comment by r10s** [comment] 2024-10-06 10:40
> IDK if a single word "existing" is enough to explain that this is not your usual "change the password" form

it is not, it is only an additional hint. but indeed, i did not look closely enough at the concrete desktop dialog, that lacks the "Log In" framing, i created an issue for that at https://github.com/deltachat/deltachat-desktop/issues/4182 and closing this issue here.

thanks a lot for bringing that up!

**Closed by r10s** 2024-10-06 10:40 UTC
